name: 'Config Git with Token'
description: 'A template to create custom GitHub Action with TypeScript/JavaScript.'
inputs:
  github-token:
    description: 'GitHub token.'
    required: false
    default: ${{ github.token }}
runs:
  using: 'node20'
  main: 'dist/index.js'
  post: 'dist/index.js'
  post-if: always()
branding:
  icon: 'user-check'
  color: 'green'
