name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main, '[0-9]+-[0-9]+-*']
  workflow_dispatch:
  workflow_run:
    workflows: ['Dependabot']
    types:
      - completed
  workflow_call:

jobs:
  test-with-github-actions-token:
    name: Test with GitHub Actions Token
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        if: ${{ github.event_name != 'workflow_run' }}

      - uses: actions/checkout@v4
        if: ${{ github.event_name == 'workflow_run' }}
        with:
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: Test with GitHub Actions token
        id: test
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  test-with-user-app-installation-token:
    name: Test with User App Installation Token
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v1
        id: get-github-app-token
        with:
          app-id: ${{ secrets.CHECK_GIT_STATUS_BOT_APP_ID }}
          private-key: ${{ secrets.CHECK_GIT_STATUS_BOT_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - uses: actions/checkout@v4
        if: ${{ github.event_name != 'workflow_run' }}
        with:
          token: ${{ steps.get-github-app-token.outputs.token }}

      - uses: actions/checkout@v4
        if: ${{ github.event_name == 'workflow_run' }}
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
          token: ${{ steps.get-github-app-token.outputs.token }}

      - name: Test
        id: test
        uses: ./
        with:
          github-token: ${{ steps.get-github-app-token.outputs.token }}

  test-with-repo-app-installation-token:
    name: Test with Repo App Installation Token
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v1
        id: get-github-app-token
        with:
          app-id: ${{ secrets.CHECK_GIT_STATUS_BOT_APP_ID }}
          private-key: ${{ secrets.CHECK_GIT_STATUS_BOT_APP_PRIVATE_KEY }}

      - uses: actions/checkout@v4
        if: ${{ github.event_name != 'workflow_run' }}
        with:
          token: ${{ steps.get-github-app-token.outputs.token }}

      - uses: actions/checkout@v4
        if: ${{ github.event_name == 'workflow_run' }}
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
          token: ${{ steps.get-github-app-token.outputs.token }}

      - name: Test
        id: test
        uses: ./
        with:
          github-token: ${{ steps.get-github-app-token.outputs.token }}

  test-with-classic-personal-access-token:
    name: Test with Classic Personal Access Token
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        if: ${{ github.event_name != 'workflow_run' }}

      - uses: actions/checkout@v4
        if: ${{ github.event_name == 'workflow_run' }}
        with:
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: Test
        id: test
        uses: ./
        with:
          github-token: ${{ secrets.CLASSIC_PERSONAL_ACCESS_TOKEN }}
